# Etape build
FROM node:16-alpine3.17 AS build

COPY . .

RUN npm i && npm run build

# Etape run
FROM node:16-alpine3.17 AS production

COPY --from=build dist dist
COPY --from=build node_modules node_modules
CMD ["node", "dist/main.js"]